# CHIIR 2026 Tutorial on Controlled Experimentation of Model Search Behaviour with Geniie-Lab

## Dataset

### Create and use a virtual environment

`venv` version

```bash
# from a shell (outside the notebook)
python3 -m venv venv
source venv/bin/activate 
```

### Install python modules

In [1]:
import sys
!{sys.executable} -m pip install ir_datasets pandas

Collecting ir_datasets
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (4.13.5)
Collecting inscriptis>=2.2.0 (from ir_datasets)
  Downloading inscriptis-2.7.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (6.0.2)
Requirement already satisfied: numpy>=1.18.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (2.0.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (6.0.3)
Requirement already satisfied: requests>=2.22.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (4.67.3)
Collecting trec-car-tools>=2.5.4 (from ir_datasets)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting lz4>=3.1.10 (from ir_datasets)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting warc3-wet>=0.2.3 (from ir_datasets)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir_datasets)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir_datasets)
  Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir_datasets)
  Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir_datasets)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->ir_datasets) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->ir_datasets) (4.15.0)
Collecting lxml>=4.5.2 (from ir_datasets)
  Downloading lxml-5.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22.0->ir_datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22.0->ir_datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22.0->ir_datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.22.0->ir_datasets) (2026.1.4)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir_datasets)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 27.9 MB/s eta 0:00:00
Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.0/149.0 kB 13.9 MB/s eta 0:00:00
Downloading inscriptis-2.7.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 4.1 MB/s eta 0:00:00
Downloading lxml-5.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (5.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 95.0 MB/s eta 0:00:00:00:01
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 52.4 MB/s eta 0:00:00
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=6569948997d6c78b29456f80861e2d57b365830f08d5679c0319366d5e373659
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55020 sha256=ca60e4a463da800e8db79467c6efb70b07f7423acad13d3f8bdc42a4e1a97dee
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, cbor, zlib-state, unlzw3, trec-car-tools, lz4, lxml, ijson, inscriptis, ir_datasets
  Attempting uninstall: lxml
    Found existing installation: lxml 6.0.2
    Uninstalling lxml-6.0.2:
      Successfully uninstalled lxml-6.0.2
Successfully installed cbor-1.0.0 ijson-3.4.0.post0 inscriptis-2.7.0 ir_datasets-0.5.11 lxml-5.4.0 lz4-4.4.5 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.10

### Obtain a dataset

We use [beir/scidocs](https://ir-datasets.com/beir.html#beir/scidocs) as an example

In [2]:
import ir_datasets
dataset_name = "beir/scidocs"
dataset = ir_datasets.load(dataset_name)

Document fields and sample data

In [3]:
print(dataset.docs_cls().__annotations__)

{'doc_id': <class 'str'>, 'text': <class 'str'>, 'title': <class 'str'>, 'authors': typing.List[str], 'year': <class 'int'>, 'cited_by': typing.List[str], 'references': typing.List[str]}

Get a sample document

In [4]:
docstore = dataset.docs_store()
doc_id='632589828c8b9fca2c3a59e97451fde8fa7d188d'
print(docstore.get(doc_id).title)
print(docstore.get(doc_id).text)

[INFO] [starting] building docstore
[INFO] [starting] opening zip file
[INFO] If you have a local copy of https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scidocs.zip, you can symlink it here to avoid downloading it again: /root/.ir_datasets/downloads/38121350fc3a4d2f48850f6aff52e4a9
[INFO] [starting] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scidocs.zip

                                                                                                                     [INFO] [finished] https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/scidocs.zip: [01:05] [142MB] [2.17MB/s]
[INFO] [finished] opening zip file [01:07]
docs_iter: 100%|████████████████████████| 25657/25657 [01:15<00:00, 340.90doc/s]
[INFO] [finished] docs_iter: [01:15] [25657doc] [340.89doc/s]
[INFO] [finished] building docstore [01:15]

A hybrid of genetic algorithm and particle swarm optimization for recurrent network design
An evolutionary recurrent network which automates the design of recurrent neural/fuzzy networks using a new evolutionary learning algorithm is proposed in this paper. This new evolutionary learning algorithm is based on a hybrid of genetic algorithm (GA) and particle swarm optimization (PSO), and is thus called HGAPSO. In HGAPSO, individuals in a new generation are created, not only by crossover and mutation operation as in GA, but also by PSO. The concept of elite strategy is adopted in HGAPSO, where the upper-half of the best-performing individuals in a population are regarded as elites. However, instead of being reproduced directly to the next generation, these elites are first enhanced. The group constituted by the elites is regarded as a swarm, and each elite corresponds to a particle within it. In this regard, the elites are enhanced by PSO, an operation which mimics the maturing phenomenon in nature. These enhanced elites constitute half of the population in the new generation, whereas the other half is generated by performing crossover and mutation operation on these enhanced elites. HGAPSO is applied to recurrent neural/fuzzy network design as follows. For recurrent neural network, a fully connected recurrent neural network is designed and applied to a temporal sequence production problem. For recurrent fuzzy network design, a Takagi-Sugeno-Kang-type recurrent fuzzy network is designed and applied to dynamic plant control. The performance of HGAPSO is compared to both GA and PSO in these recurrent networks design problems, demonstrating its superiority.

Query fields and data

In [5]:
print(dataset.queries_cls().__annotations__)

{'query_id': <class 'str'>, 'text': <class 'str'>, 'authors': typing.List[str], 'year': <class 'int'>, 'cited_by': typing.List[str], 'references': typing.List[str]}

Show queries

In [6]:
import pandas as pd
pd.DataFrame(dataset.queries_iter())

[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [1ms]

,query_id,text,authors,year,cited_by,references
0,78495383450e02c5fe817e408726134b3084905d,A Direct Search Method to solve Economic Dispa...,"[50306438, 15303316, 1976596]",2014.0,[38e78343cfd5c013decf49e8cf008ddf6458200f],"[632589828c8b9fca2c3a59e97451fde8fa7d188d, 4cf..."
1,7dcb308b9292a8bc87d6f7793d2ca5e0e19dfa40,Bearish-Bullish Sentiment Analysis on Financia...,"[2243444, 32946276, 3349721]",2017.0,"[3a3f23919a04b4ff400f6a83a72eaff80bbdfb94, 4f3...","[a08b72b072a3bf6256ddef222f6eacf014cc2b59, b1d..."
2,8c872ecd87945e71fcd9fa1b6cb1133cfe805bf2,Predicting defects in SAP Java code: An experi...,"[1816608, 2031097, 39496137, 1776543, 2000241,...",2009.0,"[2b4916a48ad3e1f5559700829297a244c54f4e9b, 425...","[1215e771ccbc06a899397230f9febf244c843174, 651..."
3,3a63667284dc8b9687ed1620406030bfe39af3c9,Active-Metric Learning for Classification of R...,"[2447432, 2818592, 15760889]",2016.0,"[7afb6785d600c0bd3cc52f658a67903abe7bc929, 0f6...","[3cf70be8b97e5831eb7c701130de618decdd4ff5, 2f0..."
4,071f47b7bc5830643e31dbed82e0375bf9b26559,Ad Hoc Retrieval Experiments Using WordNet and...,"[1921454, 37090109, 2911717, 1742723, 1695667]",1998.0,"[85b8e5fbde13b2b242558fadf1f712422d83f0eb, 414...","[356f5f4224ee090a11e83a7e3cc130b2fdb0e612, 37b..."
...,...,...,...,...,...,...
995,444a9101305d25dad8b28f466bf060ee98d922c1,Enhanced Search with Wildcards and Morphologic...,"[48626119, 38162192, 48064374, 1897943, 1754497]",2014.0,"[2e2abcd603f247ee635713b1c0e0bcedd63a2e85, 16b...","[0462a4fcd991f8d6f814337882da182c504d1d7b, 5ec..."
996,5157dde17a69f12c51186ffc20a0a6c6847f1a29,Evolutionary Cost-sensitive Extreme Learning M...,"[40613723, 1698371]",2015.0,[37e31171c98f4df077bcd0c9c2709288431f633b],"[db5aa767a0e8ceb09e7202f708e15a37bbc7ca01, 034..."
997,dc4ed2b22123596bb329221a18c8b92176fc7263,Multi-level preference regression for cold-sta...,"[2819715, 2862759, 35614655, 1771193, 39033449...",2018.0,"[43b56157e0b38d96078e157b98142954c5c5236a, ec5...","[4672f24bf1828452dc367669ab8a29f79834ad58, 82a..."
998,0cb89b20dce918778ec15c7b2a99c3e04f42d3c6,Using machine learning to optimize parallelism...,"[50986235, 1684144, 1900854, 1690319]",2017.0,"[8ecc64028c80860d3a02ffe3a02dd3dbad32cf16, 95b...","[3c0bc4e9d30719269b0048d4f36752ab964145dd, 054..."
999,89e58773fa59ef5b57f229832c2a1b3e3efff37e,Analyzing EEG signals to detect unexpected obs...,"[2492849, 6622542, 2927560, 40259975, 3334492,...",2015.0,"[37512f0a2d5ea940f4debe84593ec2c054126c1e, 518...","[f1277592f221ea26fa1d2321a38b64c58b33d75b, 42a..."

Qrel fields and data

In [7]:
print(dataset.qrels_cls().__annotations__)

{'query_id': <class 'str'>, 'doc_id': <class 'str'>, 'relevance': <class 'int'>, 'iteration': <class 'str'>}

In [8]:
pd.DataFrame(dataset.qrels_iter())

[INFO] [starting] opening zip file
[INFO] [finished] opening zip file [1ms]

,query_id,doc_id,relevance,iteration
0,78495383450e02c5fe817e408726134b3084905d,632589828c8b9fca2c3a59e97451fde8fa7d188d,1,0
1,78495383450e02c5fe817e408726134b3084905d,86e87db2dab958f1bd5877dc7d5b8105d6e31e46,1,0
2,78495383450e02c5fe817e408726134b3084905d,2a047d8c4c2a4825e0f0305294e7da14f8de6fd3,1,0
3,78495383450e02c5fe817e408726134b3084905d,506172b0e0dd4269bdcfe96dda9ea9d8602bbfb6,1,0
4,78495383450e02c5fe817e408726134b3084905d,51317b6082322a96b4570818b7a5ec8b2e330f2f,1,0
...,...,...,...,...
29923,89e58773fa59ef5b57f229832c2a1b3e3efff37e,4c98202e345a55b7b1d8c2347def21cac05935e6,0,0
29924,89e58773fa59ef5b57f229832c2a1b3e3efff37e,73ef059add8471751f661d78a0c1b0ee0dc62a19,0,0
29925,89e58773fa59ef5b57f229832c2a1b3e3efff37e,2c9bd66e9782af58a61196884a512ebbeef16859,0,0
29926,89e58773fa59ef5b57f229832c2a1b3e3efff37e,2a4423b10725e54ad72f4f1fcf77db5bc835f0a6,0,0
29927,89e58773fa59ef5b57f229832c2a1b3e3efff37e,dec997b20ebe2b867f68cc5c123d9cb9eafad6bb,0,0